apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: flint
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: anflwkd@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flint-com-tls
  namespace: flint
spec:
  secretName: flint-com-tls
  duration: 2160h #90일
  renewBefore: 360h # 15일 전에 갱신
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.flinthotels.site
  dnsNames:
    - server.flinthotels.site