name: deploy flint with k8s
on:
  push:
    branches:
      - Moori#11
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2
# 가상 pc 에 kubectl 을 설치해 주어야 한다.
      - name: install kubectl 
        uses: azure/setup-kubectl@v3
        with:
        # 너무 최신 버전을 쓰면 못 따라 올 수 있다. 우리는 1.29.몇 쓰고 있음
          version: "v1.25.9"
        id: install
      
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET}}
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name team4-flint --region ap-northeast-2

      - name: login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
#------------------------- flint -----------------------------------
      - name: build and push docker flint images to ecr
        env: 
          REPOSITORY: flint
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./Dockerfile ./
          docker push $REGISTRY/$REPOSITORY:latest
      
      - name: eks kubectl apply
        run: |
          kubectl apply -f ./k8s/flint_depl.yml
          kubectl rollout restart deployment flint-deployment -n mooo